// charades-words.js — 500+ words for Charades Generator
// Each entry: { word, category, difficulty, hint }
// Categories: animals | movies | kids | adults | actions | christmas | halloween | famous | objects | food | sports | tvshows

const CHARADES_WORDS = [

  // ── ANIMALS (55) ──────────────────────────────────────────
  { word: "Dog",           category: "animals", difficulty: "easy",   hint: "Man's best friend — barks and wags its tail" },
  { word: "Cat",           category: "animals", difficulty: "easy",   hint: "Purrs, knocks things off tables, says meow" },
  { word: "Bird",          category: "animals", difficulty: "easy",   hint: "Has wings and feathers, can fly and sing" },
  { word: "Fish",          category: "animals", difficulty: "easy",   hint: "Lives underwater, swims with fins" },
  { word: "Rabbit",        category: "animals", difficulty: "easy",   hint: "Hops, has long ears, loves carrots" },
  { word: "Horse",         category: "animals", difficulty: "easy",   hint: "Large animal you can ride, says neigh" },
  { word: "Cow",           category: "animals", difficulty: "easy",   hint: "Gives milk, says moo, lives on a farm" },
  { word: "Pig",           category: "animals", difficulty: "easy",   hint: "Pink, rolls in mud, says oink" },
  { word: "Sheep",         category: "animals", difficulty: "easy",   hint: "Fluffy white animal, gives wool, says baa" },
  { word: "Duck",          category: "animals", difficulty: "easy",   hint: "Swims on water, says quack, has a flat beak" },
  { word: "Chicken",       category: "animals", difficulty: "easy",   hint: "Lays eggs, lives on a farm, clucks" },
  { word: "Mouse",         category: "animals", difficulty: "easy",   hint: "Tiny rodent, loves cheese, squeaks" },
  { word: "Frog",          category: "animals", difficulty: "easy",   hint: "Jumps, lives near water, says ribbit" },
  { word: "Turtle",        category: "animals", difficulty: "easy",   hint: "Carries a shell on its back, moves slowly" },
  { word: "Bear",          category: "animals", difficulty: "easy",   hint: "Large furry animal, loves honey, hibernates" },
  { word: "Lion",          category: "animals", difficulty: "easy",   hint: "King of the jungle, has a big mane, roars" },
  { word: "Tiger",         category: "animals", difficulty: "easy",   hint: "Big orange cat with black stripes" },
  { word: "Elephant",      category: "animals", difficulty: "easy",   hint: "Largest land animal, has a long trunk" },
  { word: "Monkey",        category: "animals", difficulty: "easy",   hint: "Swings from trees, loves bananas" },
  { word: "Giraffe",       category: "animals", difficulty: "easy",   hint: "Very long neck, tallest animal on land" },
  { word: "Zebra",         category: "animals", difficulty: "easy",   hint: "Looks like a horse with black and white stripes" },
  { word: "Penguin",       category: "animals", difficulty: "easy",   hint: "Black and white bird, lives in Antarctica, can't fly" },
  { word: "Dolphin",       category: "animals", difficulty: "easy",   hint: "Intelligent ocean mammal, jumps and does tricks" },
  { word: "Hamster",       category: "animals", difficulty: "easy",   hint: "Tiny fluffy pet that runs on a wheel" },
  { word: "Snake",         category: "animals", difficulty: "easy",   hint: "Long reptile with no legs, slithers on the ground" },
  { word: "Flamingo",      category: "animals", difficulty: "medium", hint: "Pink bird that stands on one leg" },
  { word: "Kangaroo",      category: "animals", difficulty: "medium", hint: "Australian animal with a pouch, hops very fast" },
  { word: "Chimpanzee",    category: "animals", difficulty: "medium", hint: "Smart ape, closest relative to humans" },
  { word: "Hippopotamus",  category: "animals", difficulty: "medium", hint: "Large semi-aquatic animal, very wide mouth" },
  { word: "Crocodile",     category: "animals", difficulty: "medium", hint: "Large reptile with snapping jaws, lurks in water" },
  { word: "Octopus",       category: "animals", difficulty: "medium", hint: "Eight arms, lives in the sea, squirts ink" },
  { word: "Chameleon",     category: "animals", difficulty: "medium", hint: "Lizard that changes color, has a long sticky tongue" },
  { word: "Jellyfish",     category: "animals", difficulty: "medium", hint: "Transparent sea creature, can sting you" },
  { word: "Sea Turtle",    category: "animals", difficulty: "medium", hint: "Turtle that lives in the ocean, swims far" },
  { word: "Iguana",        category: "animals", difficulty: "medium", hint: "Large tropical lizard with spines on its back" },
  { word: "Peacock",       category: "animals", difficulty: "medium", hint: "Bird with a spectacular colorful fan tail" },
  { word: "Ostrich",       category: "animals", difficulty: "medium", hint: "World's largest bird, can't fly but runs very fast" },
  { word: "Sloth",         category: "animals", difficulty: "medium", hint: "Slowest mammal alive, hangs upside down in trees" },
  { word: "Gorilla",       category: "animals", difficulty: "medium", hint: "Largest great ape, beats its chest" },
  { word: "Panda",         category: "animals", difficulty: "medium", hint: "Black and white bear from China, eats bamboo" },
  { word: "Koala",         category: "animals", difficulty: "medium", hint: "Fluffy Australian marsupial, sleeps 22 hours a day" },
  { word: "Polar Bear",    category: "animals", difficulty: "medium", hint: "White bear that lives in the Arctic, swims in icy water" },
  { word: "Manta Ray",     category: "animals", difficulty: "medium", hint: "Large flat ocean creature that glides through water like a bird" },
  { word: "Platypus",      category: "animals", difficulty: "medium", hint: "Australian mammal with a duck bill that lays eggs" },
  { word: "Axolotl",       category: "animals", difficulty: "hard",   hint: "Smiling salamander from Mexico that stays in larval form forever" },
  { word: "Narwhal",       category: "animals", difficulty: "hard",   hint: "'Unicorn of the sea' — whale with a long spiraling tusk" },
  { word: "Pangolin",      category: "animals", difficulty: "hard",   hint: "Scaly anteater that rolls into a ball when threatened" },
  { word: "Komodo Dragon", category: "animals", difficulty: "hard",   hint: "World's largest lizard, toxic saliva, from Indonesia" },
  { word: "Capybara",      category: "animals", difficulty: "hard",   hint: "World's largest rodent, loves water, looks like a giant guinea pig" },
  { word: "Tapir",         category: "animals", difficulty: "hard",   hint: "Large pig-like animal with a short flexible trunk" },
  { word: "Wolverine",     category: "animals", difficulty: "hard",   hint: "Ferocious small bear-like animal, not the superhero" },
  { word: "Armadillo",     category: "animals", difficulty: "hard",   hint: "Armored mammal that rolls into a ball, lives in Americas" },
  { word: "Quokka",        category: "animals", difficulty: "hard",   hint: "World's happiest animal — always looks like it's smiling" },
  { word: "Mantis Shrimp", category: "animals", difficulty: "hard",   hint: "Colorful sea creature with the most powerful punch in nature" },
  { word: "Wombat",        category: "animals", difficulty: "hard",   hint: "Australian marsupial that digs burrows and produces cube-shaped droppings" },
  { word: "Bald Eagle",    category: "animals", difficulty: "medium", hint: "US national bird, white head, large wingspan" },

  // ── MOVIES (55) ───────────────────────────────────────────
  { word: "Frozen",              category: "movies", difficulty: "easy",   hint: "Disney movie — sister with ice powers, 'Let It Go'" },
  { word: "Titanic",             category: "movies", difficulty: "easy",   hint: "Ship that hits an iceberg, Jack and Rose love story" },
  { word: "Avatar",              category: "movies", difficulty: "easy",   hint: "Blue aliens on the planet Pandora" },
  { word: "Toy Story",           category: "movies", difficulty: "easy",   hint: "Cowboy doll and space ranger toys come to life" },
  { word: "The Lion King",       category: "movies", difficulty: "easy",   hint: "Disney — lion prince Simba exiled by his uncle Scar" },
  { word: "Finding Nemo",        category: "movies", difficulty: "easy",   hint: "Clownfish dad searches the ocean for his lost son" },
  { word: "Shrek",               category: "movies", difficulty: "easy",   hint: "Green ogre in a swamp, talking donkey, fairy tale parody" },
  { word: "Home Alone",          category: "movies", difficulty: "easy",   hint: "Kid left behind on Christmas defends house from burglars" },
  { word: "Moana",               category: "movies", difficulty: "easy",   hint: "Polynesian girl sails the ocean to restore the heart of Te Fiti" },
  { word: "Grease",              category: "movies", difficulty: "easy",   hint: "1950s high school musical, Danny and Sandy, leather jackets" },
  { word: "Jaws",                category: "movies", difficulty: "easy",   hint: "Giant great white shark terrorizes a beach town" },
  { word: "Bambi",               category: "movies", difficulty: "easy",   hint: "Disney — baby deer whose mother is shot by a hunter" },
  { word: "Aladdin",             category: "movies", difficulty: "easy",   hint: "Street boy finds a magic lamp with a genie in it" },
  { word: "Mulan",               category: "movies", difficulty: "easy",   hint: "Chinese girl disguises as a soldier to fight in her father's place" },
  { word: "Ratatouille",         category: "movies", difficulty: "easy",   hint: "Rat who loves cooking takes control of a famous Paris chef" },
  { word: "WALL-E",              category: "movies", difficulty: "easy",   hint: "Lonely robot cleaning Earth falls in love with another robot" },
  { word: "Up",                  category: "movies", difficulty: "easy",   hint: "Old man floats his house with balloons to South America" },
  { word: "Coco",                category: "movies", difficulty: "easy",   hint: "Mexican boy enters the Land of the Dead to find his great-great-grandfather" },
  { word: "Inside Out",          category: "movies", difficulty: "easy",   hint: "Emotions — Joy, Sadness, Fear, Anger, Disgust — control a girl's brain" },
  { word: "E.T.",                category: "movies", difficulty: "easy",   hint: "Small alien left behind on Earth, befriends a boy named Elliott" },
  { word: "The Dark Knight",     category: "movies", difficulty: "medium", hint: "Batman vs. the Joker in Gotham City" },
  { word: "Inception",           category: "movies", difficulty: "medium", hint: "Thieves enter people's dreams to steal — or plant — ideas" },
  { word: "Forrest Gump",        category: "movies", difficulty: "medium", hint: "'Life is like a box of chocolates' — simple man, extraordinary life" },
  { word: "Jurassic Park",       category: "movies", difficulty: "medium", hint: "Scientists clone dinosaurs for a theme park; dinosaurs escape" },
  { word: "Harry Potter",        category: "movies", difficulty: "medium", hint: "Boy discovers he's a wizard and attends Hogwarts School" },
  { word: "Star Wars",           category: "movies", difficulty: "medium", hint: "Space opera — Luke Skywalker, Darth Vader, lightsabers, the Force" },
  { word: "Lord of the Rings",   category: "movies", difficulty: "medium", hint: "Hobbit must destroy the One Ring in the fires of Mount Doom" },
  { word: "The Avengers",        category: "movies", difficulty: "medium", hint: "Marvel superheroes assemble to stop an alien invasion" },
  { word: "Spider-Man",          category: "movies", difficulty: "medium", hint: "Teen bitten by radioactive spider gets wall-crawling superpowers" },
  { word: "The Notebook",        category: "movies", difficulty: "medium", hint: "Old man reads a romance story to a woman with dementia" },
  { word: "La La Land",          category: "movies", difficulty: "medium", hint: "Actress and jazz musician fall in love in Los Angeles" },
  { word: "Get Out",             category: "movies", difficulty: "medium", hint: "Black man visits white girlfriend's family — something's very wrong" },
  { word: "Parasite",            category: "movies", difficulty: "medium", hint: "Korean Oscar winner — poor family infiltrates wealthy household" },
  { word: "Interstellar",        category: "movies", difficulty: "medium", hint: "Astronauts travel through a black hole to save humanity" },
  { word: "Gladiator",           category: "movies", difficulty: "medium", hint: "Roman general enslaved, becomes champion gladiator seeking revenge" },
  { word: "Mean Girls",          category: "movies", difficulty: "medium", hint: "New girl at school joins the most popular — and ruthless — clique" },
  { word: "Black Panther",       category: "movies", difficulty: "medium", hint: "King of Wakanda defends his hi-tech African nation" },
  { word: "Bridesmaids",         category: "movies", difficulty: "medium", hint: "Best friend drama as the maid of honor plans a chaotic wedding" },
  { word: "Clueless",            category: "movies", difficulty: "medium", hint: "90s Beverly Hills high school girl plays matchmaker with disastrous results" },
  { word: "The Shining",         category: "movies", difficulty: "medium", hint: "Writer goes mad in an isolated hotel: 'Here's Johnny!'" },
  { word: "Pulp Fiction",        category: "movies", difficulty: "hard",   hint: "Quentin Tarantino — intertwined crime stories in Los Angeles" },
  { word: "The Godfather",       category: "movies", difficulty: "hard",   hint: "Mafia patriarch makes 'an offer you can't refuse'" },
  { word: "Schindler's List",    category: "movies", difficulty: "hard",   hint: "German businessman saves 1,200 Jewish people during the Holocaust" },
  { word: "No Country for Old Men", category: "movies", difficulty: "hard", hint: "Unstoppable assassin with a cattle gun hunts a man across Texas" },
  { word: "2001 A Space Odyssey",category: "movies", difficulty: "hard",   hint: "HAL 9000 AI goes rogue on a mission to Jupiter; ends with a monolith" },
  { word: "Eternal Sunshine",    category: "movies", difficulty: "hard",   hint: "Heartbroken couple erases each other from their memories" },
  { word: "Drive",               category: "movies", difficulty: "hard",   hint: "Silent Hollywood stuntman moonlights as a getaway driver" },
  { word: "A Clockwork Orange",  category: "movies", difficulty: "hard",   hint: "Violent British teen subjected to aversion therapy in a dystopian future" },
  { word: "Blade Runner",        category: "movies", difficulty: "hard",   hint: "Detective in rainy neon future must retire rogue androids" },
  { word: "Apocalypse Now",      category: "movies", difficulty: "hard",   hint: "Army captain travels up a jungle river to eliminate a rogue colonel" },
  { word: "12 Angry Men",        category: "movies", difficulty: "hard",   hint: "One dissenting juror challenges 11 others to reconsider a murder verdict" },
  { word: "Chinatown",           category: "movies", difficulty: "hard",   hint: "1930s LA noir — private detective uncovers a massive water conspiracy" },
  { word: "There Will Be Blood",  category: "movies", difficulty: "hard",   hint: "Ruthless oil prospector destroys everything around him for wealth" },
  { word: "Mulholland Drive",    category: "movies", difficulty: "hard",   hint: "Surreal mystery — aspiring actress and amnesiac woman in Hollywood" },
  { word: "Requiem for a Dream", category: "movies", difficulty: "hard",   hint: "Four people destroyed by their addictions; brutal and harrowing" },

  // ── KIDS (50) ────────────────────────────────────────────
  { word: "Jumping",                 category: "kids", difficulty: "easy",   hint: "Push off the ground with both feet at the same time" },
  { word: "Running",                 category: "kids", difficulty: "easy",   hint: "Move very fast with your legs, faster than walking" },
  { word: "Drawing",                 category: "kids", difficulty: "easy",   hint: "Making pictures with a pencil or crayon on paper" },
  { word: "Sleeping",                category: "kids", difficulty: "easy",   hint: "Lying down with eyes closed, dreaming" },
  { word: "Swimming",                category: "kids", difficulty: "easy",   hint: "Moving through water using your arms and legs" },
  { word: "Dancing",                 category: "kids", difficulty: "easy",   hint: "Moving your body to music" },
  { word: "Blowing Bubbles",         category: "kids", difficulty: "easy",   hint: "Dip a wand in soapy liquid and blow gently" },
  { word: "Riding a Bike",           category: "kids", difficulty: "easy",   hint: "Pedaling on two wheels while keeping your balance" },
  { word: "Flying a Kite",           category: "kids", difficulty: "easy",   hint: "Running with a string attached to something in the sky" },
  { word: "Building Blocks",         category: "kids", difficulty: "easy",   hint: "Stacking colorful shapes to make towers or houses" },
  { word: "Brushing Teeth",          category: "kids", difficulty: "easy",   hint: "Using a small brush with paste to clean your mouth" },
  { word: "Eating Ice Cream",        category: "kids", difficulty: "easy",   hint: "Licking a cold sweet treat on a cone" },
  { word: "Hula Hoop",               category: "kids", difficulty: "easy",   hint: "Spinning a plastic ring around your waist" },
  { word: "Jump Rope",               category: "kids", difficulty: "easy",   hint: "Swinging a rope and jumping over it repeatedly" },
  { word: "Opening Presents",        category: "kids", difficulty: "easy",   hint: "Tearing the wrapping paper off a gift box" },
  { word: "Blowing Out Birthday Candles", category: "kids", difficulty: "easy", hint: "Making a wish then puffing out the flames on a cake" },
  { word: "Tying Shoes",             category: "kids", difficulty: "easy",   hint: "Making a bow with shoelaces so your shoes stay on" },
  { word: "Hopscotch",               category: "kids", difficulty: "easy",   hint: "Hopping on one foot through numbered squares drawn on the ground" },
  { word: "Playing Tag",             category: "kids", difficulty: "easy",   hint: "Chasing someone and touching them to make them 'it'" },
  { word: "Finger Painting",         category: "kids", difficulty: "easy",   hint: "Dipping your fingers in paint and making pictures" },
  { word: "Baking Cookies",          category: "kids", difficulty: "medium", hint: "Mixing dough, cutting shapes, then putting them in the oven" },
  { word: "Doing a Cartwheel",       category: "kids", difficulty: "medium", hint: "Turning sideways with your hands and feet on the ground" },
  { word: "Making a Sandcastle",     category: "kids", difficulty: "medium", hint: "Packing wet sand into a bucket and turning it upside down" },
  { word: "Playing Video Games",     category: "kids", difficulty: "medium", hint: "Sitting with a controller, staring at a screen, pressing buttons" },
  { word: "Playing the Piano",       category: "kids", difficulty: "medium", hint: "Pressing black and white keys to make music" },
  { word: "Building a Snowman",      category: "kids", difficulty: "medium", hint: "Rolling three balls of snow and stacking them, adding a carrot nose" },
  { word: "Making a Paper Airplane", category: "kids", difficulty: "medium", hint: "Folding a sheet of paper into a shape that can fly" },
  { word: "Playing Hide and Seek",   category: "kids", difficulty: "medium", hint: "Cover your eyes and count while others hide, then find them" },
  { word: "Doing Homework",          category: "kids", difficulty: "medium", hint: "Sitting at a desk after school, writing in a notebook" },
  { word: "Sledding",                category: "kids", difficulty: "medium", hint: "Riding down a snowy hill on a flat sled" },
  { word: "Magic Tricks",            category: "kids", difficulty: "medium", hint: "Making things appear and disappear while saying 'abracadabra'" },
  { word: "Making Crafts",           category: "kids", difficulty: "medium", hint: "Gluing, cutting, and decorating to make something creative" },
  { word: "Playing Cards",           category: "kids", difficulty: "medium", hint: "Dealing and shuffling a deck to play a game" },
  { word: "Telling a Joke",          category: "kids", difficulty: "medium", hint: "Setting up a punchline that makes everyone laugh" },
  { word: "Singing a Lullaby",       category: "kids", difficulty: "medium", hint: "Humming a soft gentle song to help a baby sleep" },
  { word: "Origami",                 category: "kids", difficulty: "hard",   hint: "Japanese art of folding paper into animals and shapes without cutting" },
  { word: "Learning to Skateboard",  category: "kids", difficulty: "hard",   hint: "Standing on a board with wheels and trying not to fall" },
  { word: "Science Experiment",      category: "kids", difficulty: "hard",   hint: "Mixing chemicals in beakers and writing down what happens" },
  { word: "Playing Chess",           category: "kids", difficulty: "hard",   hint: "Moving pieces — kings, queens, knights — on a checkered board" },
  { word: "Juggling",                category: "kids", difficulty: "hard",   hint: "Keeping three or more objects in the air at once" },
  { word: "Writing a Story",         category: "kids", difficulty: "hard",   hint: "Inventing characters and adventures, then writing them down" },
  { word: "Solving a Rubik's Cube",  category: "kids", difficulty: "hard",   hint: "Twisting a colorful six-sided puzzle until each face is one color" },
  { word: "Making a Volcano",        category: "kids", difficulty: "hard",   hint: "Baking soda + vinegar in a papier-mâché mountain for a science fair" },
  { word: "Learning Sign Language",  category: "kids", difficulty: "hard",   hint: "Communicating by making specific hand shapes instead of speaking" },
  { word: "Coding",                  category: "kids", difficulty: "hard",   hint: "Typing instructions into a computer to make a program run" },
  { word: "Making Pottery",          category: "kids", difficulty: "hard",   hint: "Shaping wet clay on a spinning wheel into a bowl or vase" },
  { word: "Astronomy",               category: "kids", difficulty: "hard",   hint: "Pointing a telescope at the sky to look at stars and planets" },
  { word: "Learning to Knit",        category: "kids", difficulty: "hard",   hint: "Using two needles and yarn to create a loop-by-loop fabric" },
  { word: "Performing in a Play",    category: "kids", difficulty: "hard",   hint: "Memorizing lines, wearing a costume, acting on a stage" },
  { word: "Making a Kite",           category: "kids", difficulty: "hard",   hint: "Building a frame with sticks and paper, adding a long string tail" },

  // ── ADULTS (50) ──────────────────────────────────────────
  { word: "Drinking Coffee",        category: "adults", difficulty: "easy",   hint: "Morning ritual — hot dark liquid that wakes you up" },
  { word: "Yoga",                   category: "adults", difficulty: "easy",   hint: "Slow stretching poses on a mat, often with deep breathing" },
  { word: "Shopping",               category: "adults", difficulty: "easy",   hint: "Walking through a mall with bags, looking at prices" },
  { word: "Cooking Dinner",         category: "adults", difficulty: "easy",   hint: "Chopping vegetables and stirring pots at the stove" },
  { word: "Driving",                category: "adults", difficulty: "easy",   hint: "Turning a steering wheel, pressing pedals, watching the road" },
  { word: "Texting",                category: "adults", difficulty: "easy",   hint: "Typing a message on your phone with your thumbs" },
  { word: "Reading",                category: "adults", difficulty: "easy",   hint: "Sitting quietly turning pages of a book" },
  { word: "Going to the Gym",       category: "adults", difficulty: "easy",   hint: "Lifting weights and running on treadmills in a sweaty room" },
  { word: "Taking a Selfie",        category: "adults", difficulty: "easy",   hint: "Holding your phone at arm's length and smiling at the camera" },
  { word: "Grocery Shopping",       category: "adults", difficulty: "easy",   hint: "Pushing a cart through supermarket aisles, checking a list" },
  { word: "Washing Dishes",         category: "adults", difficulty: "easy",   hint: "Scrubbing plates and glasses under running water" },
  { word: "Making the Bed",         category: "adults", difficulty: "easy",   hint: "Pulling up sheets and fluffing pillows in the morning" },
  { word: "Taking Out the Trash",   category: "adults", difficulty: "easy",   hint: "Tying up the garbage bag and dragging the bin to the curb" },
  { word: "Ordering Food Delivery", category: "adults", difficulty: "easy",   hint: "Tapping an app on your phone; someone brings food to your door" },
  { word: "Watching Netflix",       category: "adults", difficulty: "easy",   hint: "Lying on the couch staring at a TV for five hours straight" },
  { word: "Rock Climbing",          category: "adults", difficulty: "medium", hint: "Gripping holds on a tall wall or cliff, wearing a harness" },
  { word: "Wine Tasting",           category: "adults", difficulty: "medium", hint: "Swirling, sniffing, and sipping small pours while saying 'notes of oak'" },
  { word: "Online Dating",          category: "adults", difficulty: "medium", hint: "Swiping left or right on strangers' photos hoping to find love" },
  { word: "Binge Watching",         category: "adults", difficulty: "medium", hint: "Watching six episodes in a row and ignoring all responsibilities" },
  { word: "Road Trip",              category: "adults", difficulty: "medium", hint: "Long drive with snacks, playlists, and frequent rest stops" },
  { word: "Meditation",             category: "adults", difficulty: "medium", hint: "Sitting still with closed eyes, focusing only on your breathing" },
  { word: "Working from Home",      category: "adults", difficulty: "medium", hint: "Attending Zoom calls in a shirt and pajama bottoms" },
  { word: "Video Conferencing",     category: "adults", difficulty: "medium", hint: "Talking to a grid of tiny faces on a laptop screen" },
  { word: "Public Speaking",        category: "adults", difficulty: "medium", hint: "Standing at a podium addressing a crowd while trying not to panic" },
  { word: "Job Interview",          category: "adults", difficulty: "medium", hint: "Sitting across from a stranger trying to sell yourself in 30 minutes" },
  { word: "First Date",             category: "adults", difficulty: "medium", hint: "Nervous dinner with someone you just met, trying to be charming" },
  { word: "Moving Apartments",      category: "adults", difficulty: "medium", hint: "Carrying boxes up stairs, dropping the couch on the landing" },
  { word: "Getting a Tattoo",       category: "adults", difficulty: "medium", hint: "Lying still while someone buzzes permanent ink into your skin" },
  { word: "Happy Hour",             category: "adults", difficulty: "medium", hint: "After-work drinks with colleagues at discounted prices" },
  { word: "Networking",             category: "adults", difficulty: "medium", hint: "Handing out business cards and making small talk at a conference" },
  { word: "Going on a Diet",        category: "adults", difficulty: "medium", hint: "Eating salads all week and staring longingly at the bread basket" },
  { word: "Working Overtime",       category: "adults", difficulty: "medium", hint: "Still at the office when everyone else has already gone home" },
  { word: "Doing Taxes",            category: "adults", difficulty: "hard",   hint: "Filling out forms, collecting receipts, dreading April 15th" },
  { word: "Negotiating a Raise",    category: "adults", difficulty: "hard",   hint: "Sitting across from your boss listing your achievements nervously" },
  { word: "Writing a Will",         category: "adults", difficulty: "hard",   hint: "Legal document deciding who gets your stuff after you die" },
  { word: "Jury Duty",              category: "adults", difficulty: "hard",   hint: "Sitting in a courtroom listening to lawyers argue for days" },
  { word: "Getting a Mortgage",     category: "adults", difficulty: "hard",   hint: "Signing a 30-year agreement to pay for a house you barely afford" },
  { word: "Starting a Business",    category: "adults", difficulty: "hard",   hint: "Quitting your job and sinking savings into an idea that might fail" },
  { word: "Parallel Parking",       category: "adults", difficulty: "hard",   hint: "Reversing a car into a tiny space between two other cars" },
  { word: "Dealing with Insurance", category: "adults", difficulty: "hard",   hint: "On hold for 45 minutes explaining the same accident for the fifth time" },
  { word: "Being Stuck in Traffic", category: "adults", difficulty: "hard",   hint: "Sitting in a long line of cars, barely moving, furiously late" },
  { word: "Identity Theft",         category: "adults", difficulty: "hard",   hint: "Discovering a stranger has been living your financial life" },
  { word: "Filing a Lawsuit",       category: "adults", difficulty: "hard",   hint: "Hiring a lawyer and taking someone to court over a dispute" },
  { word: "Stock Market Trading",   category: "adults", difficulty: "hard",   hint: "Staring at green and red numbers on a screen, sweating" },
  { word: "Retirement Planning",    category: "adults", difficulty: "hard",   hint: "Calculating how much money you need to never work again" },
  { word: "Going Viral",            category: "adults", difficulty: "hard",   hint: "Waking up to find your video has 10 million strangers watching it" },
  { word: "Commuting",              category: "adults", difficulty: "medium", hint: "Crushed between strangers on a packed subway train every morning" },
  { word: "Adulting",               category: "adults", difficulty: "medium", hint: "Doing laundry, paying bills, and pretending you have it all figured out" },
  { word: "Running for Office",     category: "adults", difficulty: "hard",   hint: "Shaking hands, kissing babies, and giving speeches to get elected" },
  { word: "Getting a Promotion",    category: "adults", difficulty: "hard",   hint: "Being called into your boss's office and getting great news" },

  // ── ACTIONS (45) ──────────────────────────────────────────
  { word: "Surfing",                 category: "actions", difficulty: "medium", hint: "Standing on a board and riding ocean waves to shore" },
  { word: "Skydiving",               category: "actions", difficulty: "medium", hint: "Jumping out of a plane and freefalling before pulling a cord" },
  { word: "Archery",                 category: "actions", difficulty: "medium", hint: "Pulling back a bowstring and releasing an arrow at a target" },
  { word: "Fencing",                 category: "actions", difficulty: "medium", hint: "Two people in white suits lunging at each other with thin swords" },
  { word: "Ice Skating",             category: "actions", difficulty: "medium", hint: "Gliding on a frozen surface with blades strapped to your feet" },
  { word: "Skateboarding",           category: "actions", difficulty: "medium", hint: "Riding a wooden board on four wheels, doing kick flips" },
  { word: "Snowboarding",            category: "actions", difficulty: "medium", hint: "Strapped sideways to a board, sliding down a snowy mountain" },
  { word: "Scuba Diving",            category: "actions", difficulty: "medium", hint: "Breathing from a tank underwater while exploring coral reefs" },
  { word: "Horseback Riding",        category: "actions", difficulty: "medium", hint: "Sitting atop a large animal, directing it with your legs and reins" },
  { word: "Bungee Jumping",          category: "actions", difficulty: "medium", hint: "Leaping off a bridge tied to a huge elastic cord" },
  { word: "Parkour",                 category: "actions", difficulty: "medium", hint: "Leaping between walls, vaulting fences, running across rooftops" },
  { word: "Glassblowing",            category: "actions", difficulty: "medium", hint: "Blowing through a long pipe to inflate a blob of molten glass" },
  { word: "Pottery",                 category: "actions", difficulty: "medium", hint: "Centering spinning wet clay on a wheel to form a vase or bowl" },
  { word: "Knitting",                category: "actions", difficulty: "easy",   hint: "Looping yarn through loops with two long needles to make fabric" },
  { word: "Gardening",               category: "actions", difficulty: "easy",   hint: "Digging in soil, planting seeds, watering flowers" },
  { word: "Hiking",                  category: "actions", difficulty: "easy",   hint: "Walking on a trail through nature, wearing boots and a backpack" },
  { word: "Fishing",                 category: "actions", difficulty: "easy",   hint: "Holding a rod by water, waiting for a tug on the line" },
  { word: "Bowling",                 category: "actions", difficulty: "easy",   hint: "Rolling a heavy ball down a lane to knock down pins" },
  { word: "Photography",             category: "actions", difficulty: "easy",   hint: "Pointing a camera and pressing a button to capture a moment" },
  { word: "Painting",                category: "actions", difficulty: "easy",   hint: "Dipping a brush in color and spreading it on a canvas" },
  { word: "Singing",                 category: "actions", difficulty: "easy",   hint: "Opening your mouth and making music with your voice" },
  { word: "Writing",                 category: "actions", difficulty: "easy",   hint: "Moving a pen across paper to form words and sentences" },
  { word: "Cooking",                 category: "actions", difficulty: "easy",   hint: "Preparing food using heat — boiling, frying, baking" },
  { word: "Juggling Flaming Torches",category: "actions", difficulty: "hard",   hint: "Keeping lit fire sticks airborne simultaneously — don't drop them" },
  { word: "Synchronized Swimming",   category: "actions", difficulty: "hard",   hint: "Team of swimmers performing choreographed moves in perfect unison" },
  { word: "Pole Vaulting",           category: "actions", difficulty: "hard",   hint: "Sprinting with a long flexible pole, planting it to launch over a high bar" },
  { word: "Bull Riding",             category: "actions", difficulty: "hard",   hint: "Holding on with one hand to an enraged bucking bull for 8 seconds" },
  { word: "Cave Diving",             category: "actions", difficulty: "hard",   hint: "Swimming through flooded underground caves with tanks on your back" },
  { word: "Free Solo Climbing",      category: "actions", difficulty: "hard",   hint: "Scaling a vertical cliff face with no ropes, no safety gear" },
  { word: "Wing Suit Flying",        category: "actions", difficulty: "hard",   hint: "Wearing a suit with fabric wings and gliding like a flying squirrel" },
  { word: "Knife Throwing",          category: "actions", difficulty: "hard",   hint: "Hurling sharp blades at a spinning wooden target board" },
  { word: "Tightrope Walking",       category: "actions", difficulty: "hard",   hint: "Balancing with arms outstretched on a thin wire high above the ground" },
  { word: "Fire Breathing",          category: "actions", difficulty: "hard",   hint: "Taking fuel into your mouth and blowing it toward a flame" },
  { word: "Aerial Silks",            category: "actions", difficulty: "hard",   hint: "Wrapping long fabric ribbons around your body to perform acrobatics mid-air" },
  { word: "Storm Chasing",           category: "actions", difficulty: "hard",   hint: "Driving toward tornadoes to collect scientific data up close" },
  { word: "Freediving",              category: "actions", difficulty: "hard",   hint: "Diving deep underwater on a single breath of air, no tank" },
  { word: "Yoga",                    category: "actions", difficulty: "easy",   hint: "Holding slow stretching poses and breathing mindfully on a mat" },
  { word: "Boxing",                  category: "actions", difficulty: "easy",   hint: "Throwing punches with padded gloves at another person in a ring" },
  { word: "Meditation",              category: "actions", difficulty: "easy",   hint: "Sitting very still with closed eyes, emptying your mind" },
  { word: "Weightlifting",           category: "actions", difficulty: "medium", hint: "Pressing a loaded bar above your head, straining and grimacing" },
  { word: "Rock Climbing",           category: "actions", difficulty: "medium", hint: "Pulling yourself up a sheer rock wall gripping tiny holds" },
  { word: "Ballet",                  category: "actions", difficulty: "medium", hint: "Graceful dance on tippy toes in a tutu, arms extended elegantly" },
  { word: "Kayaking",                category: "actions", difficulty: "medium", hint: "Paddling a small enclosed boat through rapids or calm water" },
  { word: "Paragliding",             category: "actions", difficulty: "hard",   hint: "Running off a hill and soaring with a parachute-like wing above you" },
  { word: "Mountain Biking",         category: "actions", difficulty: "medium", hint: "Riding a bicycle down rocky dirt trails at high speed" },

  // ── CHRISTMAS (40) ───────────────────────────────────────
  { word: "Santa Claus",            category: "christmas", difficulty: "easy",   hint: "Fat bearded man in a red suit who delivers gifts on Christmas Eve" },
  { word: "Christmas Tree",         category: "christmas", difficulty: "easy",   hint: "Decorated evergreen tree with lights and ornaments inside your house" },
  { word: "Snowman",                category: "christmas", difficulty: "easy",   hint: "Three snowballs stacked up with a carrot nose and a top hat" },
  { word: "Gift Wrapping",          category: "christmas", difficulty: "easy",   hint: "Covering a present in paper and adding a ribbon bow" },
  { word: "Reindeer",               category: "christmas", difficulty: "easy",   hint: "Flying deer that pull Santa's sleigh on Christmas Eve" },
  { word: "Christmas Stocking",     category: "christmas", difficulty: "easy",   hint: "Large sock hung by the fireplace for small gifts on Christmas morning" },
  { word: "Elf",                    category: "christmas", difficulty: "easy",   hint: "Small pointed-eared helper who makes toys in Santa's workshop" },
  { word: "Candy Cane",             category: "christmas", difficulty: "easy",   hint: "Red and white striped peppermint hook-shaped Christmas candy" },
  { word: "Christmas Lights",       category: "christmas", difficulty: "easy",   hint: "Strings of colorful blinking bulbs hung on the house outside" },
  { word: "Nativity Scene",         category: "christmas", difficulty: "easy",   hint: "Small figurines of Mary, Joseph, baby Jesus, and the three wise men" },
  { word: "Mrs. Claus",             category: "christmas", difficulty: "easy",   hint: "Santa's wife — white-haired woman in a red and white apron" },
  { word: "Christmas Cookies",      category: "christmas", difficulty: "easy",   hint: "Star and tree-shaped biscuits with icing that you bake in December" },
  { word: "Wreath",                 category: "christmas", difficulty: "easy",   hint: "Circular decoration made of holly and berries hung on the front door" },
  { word: "Star on Top",            category: "christmas", difficulty: "easy",   hint: "Golden ornament that crowns the very top of the Christmas tree" },
  { word: "Christmas Bell",         category: "christmas", difficulty: "easy",   hint: "Metal bell that rings to signal Christmas joy — jingle jingle" },
  { word: "Christmas Carol",        category: "christmas", difficulty: "medium", hint: "Going door to door singing 'Silent Night' or 'Deck the Halls'" },
  { word: "Mistletoe",              category: "christmas", difficulty: "medium", hint: "Green plant hung in doorways — you must kiss anyone standing under it" },
  { word: "Advent Calendar",        category: "christmas", difficulty: "medium", hint: "24 little doors you open one per day counting down to Christmas" },
  { word: "Elf on the Shelf",       category: "christmas", difficulty: "medium", hint: "Toy elf that 'moves' around the house each night to spy for Santa" },
  { word: "Gingerbread House",      category: "christmas", difficulty: "medium", hint: "Edible house made of gingerbread panels and icing glue" },
  { word: "Christmas Dinner",       category: "christmas", difficulty: "medium", hint: "Big family meal — turkey or ham, stuffing, and cranberry sauce" },
  { word: "Ugly Sweater Party",     category: "christmas", difficulty: "medium", hint: "Everyone wears the most garish, tacky holiday sweater they own" },
  { word: "Decorating the Tree",    category: "christmas", difficulty: "medium", hint: "Hanging baubles and tinsel on a pine tree while arguing about who gets the star" },
  { word: "Holiday Shopping",       category: "christmas", difficulty: "medium", hint: "Rushing through crowded malls on December 23rd buying last-minute gifts" },
  { word: "Secret Santa",           category: "christmas", difficulty: "medium", hint: "Office gift exchange where you anonymously buy a present for one person" },
  { word: "Yule Log",               category: "christmas", difficulty: "medium", hint: "Traditional large log burned in the fireplace all Christmas Day" },
  { word: "Christmas Eve",          category: "christmas", difficulty: "medium", hint: "Night before Christmas — children leave out milk and cookies for Santa" },
  { word: "Christmas Morning",      category: "christmas", difficulty: "medium", hint: "Running downstairs at 6am to find gifts magically appeared overnight" },
  { word: "Boxing Day",             category: "christmas", difficulty: "medium", hint: "December 26th — day for sales, sports, and eating Christmas leftovers" },
  { word: "Christmas Parade",       category: "christmas", difficulty: "medium", hint: "Floats and marching bands and Santa on a sleigh down Main Street" },
  { word: "Scrooge",                category: "christmas", difficulty: "hard",   hint: "Dickens character — miserly old man visited by three spirits on Christmas Eve" },
  { word: "Figgy Pudding",          category: "christmas", difficulty: "hard",   hint: "'Now bring us some figgy pudding!' — sticky British Christmas dessert" },
  { word: "Wassailing",             category: "christmas", difficulty: "hard",   hint: "Medieval tradition of drinking hot spiced cider and singing in orchards" },
  { word: "Krampus",                category: "christmas", difficulty: "hard",   hint: "Horned Austrian demon who punishes naughty children at Christmas" },
  { word: "Feast of the Seven Fishes", category: "christmas", difficulty: "hard", hint: "Italian-American Christmas Eve tradition of eating seven different seafood dishes" },
  { word: "Pantomime",              category: "christmas", difficulty: "hard",   hint: "British Christmas theater tradition with audience shouts of 'He's behind you!'" },
  { word: "Winter Solstice",        category: "christmas", difficulty: "hard",   hint: "Shortest day of the year — ancient celebration of the sun's return" },
  { word: "St. Nicholas Day",       category: "christmas", difficulty: "hard",   hint: "December 6th — European tradition where children leave shoes out for gifts" },
  { word: "The Nutcracker Ballet",  category: "christmas", difficulty: "hard",   hint: "Classic Christmas performance — toy soldier fights the Mouse King" },
  { word: "A Christmas Carol",      category: "christmas", difficulty: "hard",   hint: "Dickens story where Scrooge is redeemed by three ghostly visits" },

  // ── HALLOWEEN (40) ───────────────────────────────────────
  { word: "Pumpkin",               category: "halloween", difficulty: "easy",   hint: "Large orange gourd you carve a face into on Halloween" },
  { word: "Ghost",                 category: "halloween", difficulty: "easy",   hint: "White floating spirit that says 'boo' and passes through walls" },
  { word: "Witch",                 category: "halloween", difficulty: "easy",   hint: "Woman in a pointy black hat who flies on a broomstick" },
  { word: "Vampire",               category: "halloween", difficulty: "easy",   hint: "Creature in a black cape, drinks blood, sleeps in a coffin" },
  { word: "Skeleton",              category: "halloween", difficulty: "easy",   hint: "All your bones with no skin — the inside of you" },
  { word: "Bat",                   category: "halloween", difficulty: "easy",   hint: "Small flying mammal that sleeps upside down and comes out at night" },
  { word: "Spider",                category: "halloween", difficulty: "easy",   hint: "Eight-legged creature that spins webs to catch flies" },
  { word: "Trick or Treat",        category: "halloween", difficulty: "easy",   hint: "Kids in costumes knock on doors demanding candy" },
  { word: "Black Cat",             category: "halloween", difficulty: "easy",   hint: "Halloween symbol — dark feline said to bring bad luck if it crosses your path" },
  { word: "Haunted House",         category: "halloween", difficulty: "easy",   hint: "Spooky building full of jump scares you walk through at Halloween" },
  { word: "Full Moon",             category: "halloween", difficulty: "easy",   hint: "Bright round moon visible all night — bad things happen on these nights" },
  { word: "Jack-o-Lantern",        category: "halloween", difficulty: "easy",   hint: "Pumpkin with a carved scary face and a candle glowing inside" },
  { word: "Frankenstein",          category: "halloween", difficulty: "easy",   hint: "Monster made from dead body parts and brought to life with electricity" },
  { word: "Zombie",                category: "halloween", difficulty: "easy",   hint: "Undead person that shambles and moans and eats brains" },
  { word: "Candy Corn",            category: "halloween", difficulty: "easy",   hint: "Tricolor yellow-orange-white triangle candy everyone argues about" },
  { word: "Werewolf",              category: "halloween", difficulty: "medium", hint: "Human that transforms into a wolf under the full moon" },
  { word: "Cauldron",              category: "halloween", difficulty: "medium", hint: "Large black pot a witch uses to brew a bubbling green potion" },
  { word: "Mummy",                 category: "halloween", difficulty: "medium", hint: "Ancient Egyptian corpse wrapped in white bandages" },
  { word: "Dracula",               category: "halloween", difficulty: "medium", hint: "Famous Transylvanian vampire count who sleeps in a coffin" },
  { word: "Headless Horseman",     category: "halloween", difficulty: "medium", hint: "Galloping ghost who throws a flaming pumpkin head at terrified travelers" },
  { word: "Monster Mash",          category: "halloween", difficulty: "medium", hint: "Famous Halloween novelty song where monsters throw a dance party" },
  { word: "Séance",                category: "halloween", difficulty: "medium", hint: "Group around a table trying to contact the spirit of a dead person" },
  { word: "Graveyard",             category: "halloween", difficulty: "medium", hint: "Fenced area with tombstones marking where dead people are buried" },
  { word: "Coffin",                category: "halloween", difficulty: "medium", hint: "Rectangular wooden box a vampire sleeps in — or is buried in" },
  { word: "Scarecrow",             category: "halloween", difficulty: "medium", hint: "Stuffed dummy on a post in a field that's supposed to frighten birds" },
  { word: "Bloody Mary",           category: "halloween", difficulty: "medium", hint: "Say her name three times in a dark mirror — she appears" },
  { word: "Clown",                 category: "halloween", difficulty: "medium", hint: "Big red shoes, painted face, huge colorful hair — very unsettling at night" },
  { word: "Devil",                 category: "halloween", difficulty: "medium", hint: "Red costume with horns, pointy tail, and a pitchfork" },
  { word: "Cobwebs",               category: "halloween", difficulty: "medium", hint: "Dusty old spider webs stretched across corners of a spooky house" },
  { word: "Blood Moon",            category: "halloween", difficulty: "medium", hint: "Lunar eclipse that turns the full moon a terrifying deep red" },
  { word: "Catacombs",             category: "halloween", difficulty: "hard",   hint: "Underground burial tunnels beneath Paris lined with millions of skulls" },
  { word: "Samhain",               category: "halloween", difficulty: "hard",   hint: "Ancient Celtic festival that Halloween evolved from — veil between worlds thins" },
  { word: "Day of the Dead",       category: "halloween", difficulty: "hard",   hint: "Mexican holiday honoring deceased relatives with altars of photos and food" },
  { word: "Ouija Board",           category: "halloween", difficulty: "hard",   hint: "Board with letters used to supposedly communicate with spirits" },
  { word: "Banshee",               category: "halloween", difficulty: "hard",   hint: "Irish spirit whose piercing wail warns a family that someone is about to die" },
  { word: "Wendigo",               category: "halloween", difficulty: "hard",   hint: "Terrifying Native American spirit — human turned cannibalistic forest monster" },
  { word: "Poltergeist",           category: "halloween", difficulty: "hard",   hint: "Invisible ghost that moves objects, slams doors, and causes chaos" },
  { word: "Necromancer",           category: "halloween", difficulty: "hard",   hint: "Dark wizard who raises the dead and controls undead armies" },
  { word: "Doppelganger",          category: "halloween", difficulty: "hard",   hint: "Your exact lookalike — seeing one is considered a very bad omen" },
  { word: "Shadow People",         category: "halloween", difficulty: "hard",   hint: "Dark humanoid silhouettes glimpsed at the edge of your vision" },

  // ── FAMOUS PEOPLE (40) ───────────────────────────────────
  { word: "Elvis Presley",         category: "famous", difficulty: "medium", hint: "King of Rock and Roll — hip swivels, 'Blue Suede Shoes'" },
  { word: "Marilyn Monroe",        category: "famous", difficulty: "medium", hint: "Famous blonde actress, white dress over subway grate" },
  { word: "Michael Jackson",       category: "famous", difficulty: "medium", hint: "King of Pop — moonwalk, 'Thriller', single white glove" },
  { word: "Muhammad Ali",          category: "famous", difficulty: "medium", hint: "'Float like a butterfly, sting like a bee' — boxing legend" },
  { word: "Albert Einstein",       category: "famous", difficulty: "medium", hint: "Wild white hair, E=mc², theory of relativity, genius physicist" },
  { word: "Abraham Lincoln",       category: "famous", difficulty: "medium", hint: "Tall hat, beard, freed the slaves, 16th US president" },
  { word: "Queen Elizabeth",       category: "famous", difficulty: "medium", hint: "British monarch who reigned for 70 years, always wore bright colors" },
  { word: "Oprah Winfrey",         category: "famous", difficulty: "medium", hint: "Legendary talk show host: 'You get a car! You get a car!'" },
  { word: "Beyoncé",               category: "famous", difficulty: "medium", hint: "Queen Bey — superstar singer, Destiny's Child, Lemonade album" },
  { word: "Taylor Swift",          category: "famous", difficulty: "medium", hint: "Country-turned-pop singer who writes songs about her exes" },
  { word: "LeBron James",          category: "famous", difficulty: "medium", hint: "NBA superstar — 'The King', plays basketball and was in Space Jam 2" },
  { word: "Elon Musk",             category: "famous", difficulty: "medium", hint: "Tesla, SpaceX, bought Twitter — world's richest on-and-off man" },
  { word: "Barack Obama",          category: "famous", difficulty: "medium", hint: "44th US president — first Black president, 'Yes We Can'" },
  { word: "Dwayne Johnson",        category: "famous", difficulty: "medium", hint: "'The Rock' — wrestler turned actor, extremely muscular, very charming" },
  { word: "Adele",                 category: "famous", difficulty: "medium", hint: "British singer with a powerful voice, 'Hello', 'Rolling in the Deep'" },
  { word: "Lady Gaga",             category: "famous", difficulty: "medium", hint: "Pop star known for outrageous costumes including the meat dress" },
  { word: "Rihanna",               category: "famous", difficulty: "medium", hint: "Barbadian pop star turned billionaire beauty mogul — Fenty empire" },
  { word: "Jay-Z",                 category: "famous", difficulty: "medium", hint: "Hip-hop mogul, Beyoncé's husband, started from the Marcy projects" },
  { word: "Kanye West",            category: "famous", difficulty: "medium", hint: "Rapper who interrupted Taylor Swift's speech and ran for president" },
  { word: "Katy Perry",            category: "famous", difficulty: "medium", hint: "Singer who kissed a girl and liked it, firework pop anthems" },
  { word: "Nikola Tesla",          category: "famous", difficulty: "hard",   hint: "Inventor of alternating current electricity — feud with Edison" },
  { word: "Florence Nightingale",  category: "famous", difficulty: "hard",   hint: "Founder of modern nursing, carried a lamp through Crimean War hospitals" },
  { word: "Leonardo da Vinci",     category: "famous", difficulty: "hard",   hint: "Renaissance genius who painted the Mona Lisa and designed flying machines" },
  { word: "Napoleon Bonaparte",    category: "famous", difficulty: "hard",   hint: "Short French emperor who conquered most of Europe" },
  { word: "Cleopatra",             category: "famous", difficulty: "hard",   hint: "Last pharaoh of ancient Egypt, famous for beauty and political genius" },
  { word: "Aristotle",             category: "famous", difficulty: "hard",   hint: "Ancient Greek philosopher who tutored Alexander the Great" },
  { word: "Genghis Khan",          category: "famous", difficulty: "hard",   hint: "Mongolian conqueror who built the largest contiguous empire in history" },
  { word: "Joan of Arc",           category: "famous", difficulty: "hard",   hint: "Teenage French peasant girl who led armies to victory, then burned at the stake" },
  { word: "Galileo Galilei",       category: "famous", difficulty: "hard",   hint: "Astronomer who proved Earth orbits the Sun and was tried for heresy" },
  { word: "Sigmund Freud",         category: "famous", difficulty: "hard",   hint: "Father of psychoanalysis — blamed everything on your mother" },
  { word: "Karl Marx",             category: "famous", difficulty: "hard",   hint: "German philosopher who wrote The Communist Manifesto" },
  { word: "Isaac Newton",          category: "famous", difficulty: "hard",   hint: "Apple fell on his head and he discovered gravity" },
  { word: "Shakespeare",           category: "famous", difficulty: "hard",   hint: "Elizabethan playwright: Romeo and Juliet, Hamlet, 'To be or not to be'" },
  { word: "Mozart",                category: "famous", difficulty: "hard",   hint: "Child prodigy who composed symphonies before age 10" },
  { word: "Marie Curie",           category: "famous", difficulty: "hard",   hint: "First woman to win a Nobel Prize — discovered radium and polonium" },
  { word: "Charles Darwin",        category: "famous", difficulty: "hard",   hint: "Proposed the theory of evolution on the HMS Beagle voyage" },
  { word: "Julius Caesar",         category: "famous", difficulty: "hard",   hint: "Roman general and dictator, stabbed 23 times in the Senate — 'Et tu, Brute?'" },
  { word: "Cleopatra",             category: "famous", difficulty: "hard",   hint: "Last pharaoh of ancient Egypt, allied with Caesar then Mark Antony" },
  { word: "Beethoven",             category: "famous", difficulty: "hard",   hint: "Composed his greatest symphonies after going completely deaf" },
  { word: "Copernicus",            category: "famous", difficulty: "hard",   hint: "First to propose that Earth orbits the Sun, not the other way around" },

  // ── OBJECTS (40) ──────────────────────────────────────────
  { word: "Chair",            category: "objects", difficulty: "easy",   hint: "Four legs, a seat, and a back — you sit on it" },
  { word: "Table",            category: "objects", difficulty: "easy",   hint: "Flat surface on legs — you eat, work, and put things on it" },
  { word: "Phone",            category: "objects", difficulty: "easy",   hint: "Small glass rectangle you stare at all day" },
  { word: "Book",             category: "objects", difficulty: "easy",   hint: "Pages bound together with a cover — contains stories or information" },
  { word: "Car",              category: "objects", difficulty: "easy",   hint: "Four-wheeled motor vehicle for road travel" },
  { word: "Ball",             category: "objects", difficulty: "easy",   hint: "Round object you throw, kick, or bounce" },
  { word: "Cup",              category: "objects", difficulty: "easy",   hint: "Small container with a handle for hot drinks" },
  { word: "Hat",              category: "objects", difficulty: "easy",   hint: "Covering you wear on top of your head" },
  { word: "Key",              category: "objects", difficulty: "easy",   hint: "Small metal tool that opens a lock" },
  { word: "Shoe",             category: "objects", difficulty: "easy",   hint: "Protective covering for your foot" },
  { word: "Umbrella",         category: "objects", difficulty: "easy",   hint: "Collapsible canopy on a stick that keeps rain off your head" },
  { word: "Mirror",           category: "objects", difficulty: "easy",   hint: "Reflective surface that shows you your own face" },
  { word: "Lamp",             category: "objects", difficulty: "easy",   hint: "Device with a bulb that produces light" },
  { word: "Clock",            category: "objects", difficulty: "easy",   hint: "Circular device with hands that tells you the time" },
  { word: "Pillow",           category: "objects", difficulty: "easy",   hint: "Soft cushion you rest your head on when sleeping" },
  { word: "Telescope",        category: "objects", difficulty: "medium", hint: "Long tube that makes distant stars and planets look close" },
  { word: "Microscope",       category: "objects", difficulty: "medium", hint: "Scientific instrument that magnifies things too small to see" },
  { word: "Typewriter",       category: "objects", difficulty: "medium", hint: "Old keyboard machine that stamps ink letters directly onto paper" },
  { word: "Compass",          category: "objects", difficulty: "medium", hint: "Navigational tool whose needle always points north" },
  { word: "Thermometer",      category: "objects", difficulty: "medium", hint: "Glass tube with mercury that measures how hot or cold something is" },
  { word: "Parachute",        category: "objects", difficulty: "medium", hint: "Fabric canopy that slows your fall after jumping from a plane" },
  { word: "Submarine",        category: "objects", difficulty: "medium", hint: "Underwater vessel that dives and surfaces using ballast tanks" },
  { word: "Saxophone",        category: "objects", difficulty: "medium", hint: "Curved brass instrument with keys that you blow through a mouthpiece" },
  { word: "Escalator",        category: "objects", difficulty: "medium", hint: "Moving staircase in shopping malls and airports" },
  { word: "Metronome",        category: "objects", difficulty: "medium", hint: "Ticking pendulum device that keeps precise musical tempo" },
  { word: "Vending Machine",  category: "objects", difficulty: "medium", hint: "Tall box that dispenses snacks when you insert coins and press a button" },
  { word: "Traffic Light",    category: "objects", difficulty: "medium", hint: "Pole with red, amber, and green lights that controls road traffic" },
  { word: "Wheelchair",       category: "objects", difficulty: "medium", hint: "Chair mounted on wheels for people who cannot walk" },
  { word: "Periscope",        category: "objects", difficulty: "medium", hint: "L-shaped mirror tube that lets submarines see above the surface" },
  { word: "Lawnmower",        category: "objects", difficulty: "medium", hint: "Machine with spinning blades that cuts grass to an even height" },
  { word: "Sextant",          category: "objects", difficulty: "hard",   hint: "Navigation instrument sailors used to measure angles between stars and the horizon" },
  { word: "Abacus",           category: "objects", difficulty: "hard",   hint: "Ancient calculator — rows of beads on a wooden frame" },
  { word: "Astrolabe",        category: "objects", difficulty: "hard",   hint: "Medieval brass disc used to measure the position of stars and planets" },
  { word: "Guillotine",       category: "objects", difficulty: "hard",   hint: "French Revolution execution device — heavy blade drops to sever the head" },
  { word: "Trebuchet",        category: "objects", difficulty: "hard",   hint: "Massive medieval siege catapult that hurled boulders at castle walls" },
  { word: "Orrery",           category: "objects", difficulty: "hard",   hint: "Mechanical model of the solar system showing planet orbits" },
  { word: "Stereoscope",      category: "objects", difficulty: "hard",   hint: "Victorian optical device that creates 3D images from two flat photos" },
  { word: "Daguerreotype",    category: "objects", difficulty: "hard",   hint: "First practical photographic process — silver-coated copper plate from the 1800s" },
  { word: "Zoetrope",         category: "objects", difficulty: "hard",   hint: "Spinning cylinder with sequential pictures that creates the illusion of motion" },
  { word: "Sousaphone",       category: "objects", difficulty: "hard",   hint: "Giant tuba that wraps around the player's body for marching bands" },

  // ── FOOD & DRINK (40) ────────────────────────────────────
  { word: "Pizza",            category: "food", difficulty: "easy",   hint: "Round flatbread with tomato sauce and melted cheese" },
  { word: "Burger",           category: "food", difficulty: "easy",   hint: "Beef patty in a bun with lettuce, cheese, and condiments" },
  { word: "Ice Cream",        category: "food", difficulty: "easy",   hint: "Frozen sweet dairy treat served in a cone or bowl" },
  { word: "Coffee",           category: "food", difficulty: "easy",   hint: "Hot dark bitter beverage from roasted beans that keeps you awake" },
  { word: "Apple",            category: "food", difficulty: "easy",   hint: "Red or green crunchy fruit — 'an apple a day keeps the doctor away'" },
  { word: "Banana",           category: "food", difficulty: "easy",   hint: "Yellow curved fruit monkeys love, turns brown when ripe" },
  { word: "Sandwich",         category: "food", difficulty: "easy",   hint: "Fillings between two slices of bread" },
  { word: "Cake",             category: "food", difficulty: "easy",   hint: "Layered baked sweet with frosting, often at birthday parties" },
  { word: "Hot Dog",          category: "food", difficulty: "easy",   hint: "Sausage in a long soft bun with mustard and ketchup" },
  { word: "Popcorn",          category: "food", difficulty: "easy",   hint: "Kernels that expand when heated, eaten at movie theaters" },
  { word: "Donut",            category: "food", difficulty: "easy",   hint: "Ring-shaped fried dough with glaze or sprinkles" },
  { word: "Cookie",           category: "food", difficulty: "easy",   hint: "Small flat baked sweet — chocolate chip is most popular" },
  { word: "Spaghetti",        category: "food", difficulty: "easy",   hint: "Long thin pasta twirled on a fork with tomato sauce" },
  { word: "Taco",             category: "food", difficulty: "easy",   hint: "Mexican folded tortilla with meat, cheese, and salsa inside" },
  { word: "Sushi",            category: "food", difficulty: "easy",   hint: "Japanese rice rolls wrapped in seaweed with raw fish" },
  { word: "Croissant",        category: "food", difficulty: "medium", hint: "Buttery flaky crescent-shaped French pastry" },
  { word: "Steak",            category: "food", difficulty: "medium", hint: "Thick slice of beef cooked on a grill — rare, medium, or well done" },
  { word: "Smoothie",         category: "food", difficulty: "medium", hint: "Blended fruit and yogurt drink in a tall glass" },
  { word: "Milkshake",        category: "food", difficulty: "medium", hint: "Thick cold blended ice cream drink with a straw" },
  { word: "Fondue",           category: "food", difficulty: "medium", hint: "Swiss dish — melted cheese in a pot you dip bread into" },
  { word: "Dim Sum",          category: "food", difficulty: "medium", hint: "Cantonese small dishes served in bamboo steamers at a noisy restaurant" },
  { word: "Paella",           category: "food", difficulty: "medium", hint: "Spanish rice dish cooked in a huge flat pan with seafood and saffron" },
  { word: "Ramen",            category: "food", difficulty: "medium", hint: "Japanese noodle soup with a rich broth, eggs, and toppings" },
  { word: "Falafel",          category: "food", difficulty: "medium", hint: "Middle Eastern fried chickpea balls served in pita with tahini" },
  { word: "Tiramisu",         category: "food", difficulty: "medium", hint: "Italian dessert — coffee-soaked ladyfingers layered with mascarpone cream" },
  { word: "Crème Brûlée",     category: "food", difficulty: "medium", hint: "French custard with a hard caramelized sugar crust you crack with a spoon" },
  { word: "Beef Wellington",  category: "food", difficulty: "medium", hint: "Beef tenderloin wrapped in mushroom paste and puff pastry" },
  { word: "Soufflé",          category: "food", difficulty: "medium", hint: "Fluffy baked egg dish that rises in the oven and collapses if you open it" },
  { word: "Bao Bun",          category: "food", difficulty: "medium", hint: "Soft steamed Chinese white bun folded around a filling" },
  { word: "Bruschetta",       category: "food", difficulty: "medium", hint: "Italian toasted bread rubbed with garlic, topped with tomatoes and basil" },
  { word: "Coq au Vin",       category: "food", difficulty: "hard",   hint: "Classic French chicken braised slowly in red wine with mushrooms" },
  { word: "Baklava",          category: "food", difficulty: "hard",   hint: "Middle Eastern pastry — layers of filo, nuts, and honey syrup" },
  { word: "Ceviche",          category: "food", difficulty: "hard",   hint: "Latin American raw fish 'cooked' by marinating in citrus juice" },
  { word: "Bouillabaisse",    category: "food", difficulty: "hard",   hint: "Provençal French fish stew with saffron and rouille on crusty bread" },
  { word: "Bibimbap",         category: "food", difficulty: "hard",   hint: "Korean rice bowl with arranged vegetables, egg, and gochujang sauce" },
  { word: "Shakshuka",        category: "food", difficulty: "hard",   hint: "Middle Eastern eggs poached in spiced tomato and pepper sauce" },
  { word: "Ossobuco",         category: "food", difficulty: "hard",   hint: "Milanese braised veal shank with gremolata, traditionally with risotto" },
  { word: "Rendang",          category: "food", difficulty: "hard",   hint: "Indonesian slow-cooked beef in coconut milk and spices — dry caramelized curry" },
  { word: "Goulash",          category: "food", difficulty: "hard",   hint: "Hungarian beef stew heavily seasoned with paprika" },
  { word: "Haggis",           category: "food", difficulty: "hard",   hint: "Scottish dish — sheep organs mixed with oatmeal and spices, cooked in a stomach" },

  // ── SPORTS (40) ──────────────────────────────────────────
  { word: "Football",               category: "sports", difficulty: "easy",   hint: "Oval ball sport — quarterbacks, touchdowns, Super Bowl" },
  { word: "Basketball",             category: "sports", difficulty: "easy",   hint: "Put the ball through the hoop — NBA, LeBron, slam dunks" },
  { word: "Tennis",                 category: "sports", difficulty: "easy",   hint: "Hit a fuzzy yellow ball over a net with a racket" },
  { word: "Swimming",               category: "sports", difficulty: "easy",   hint: "Racing through water using different strokes — freestyle, backstroke" },
  { word: "Soccer",                 category: "sports", difficulty: "easy",   hint: "Kick a black and white ball into a large net — the world's most popular sport" },
  { word: "Baseball",               category: "sports", difficulty: "easy",   hint: "Hit a ball with a wooden bat and run around four bases" },
  { word: "Running",                category: "sports", difficulty: "easy",   hint: "Moving very fast on foot — sprinting 100m or marathons 26 miles" },
  { word: "Golf",                   category: "sports", difficulty: "easy",   hint: "Hit a tiny white ball into a tiny hole with a club — takes 18 holes" },
  { word: "Boxing",                 category: "sports", difficulty: "easy",   hint: "Two people punch each other in a ring wearing padded gloves" },
  { word: "Volleyball",             category: "sports", difficulty: "easy",   hint: "Six players hit a ball over a high net without letting it touch the floor" },
  { word: "Skiing",                 category: "sports", difficulty: "easy",   hint: "Two long planks on your feet gliding down a snowy mountain" },
  { word: "Cycling",                category: "sports", difficulty: "easy",   hint: "Racing bikes — Tour de France, tight lycra, drafting in a peloton" },
  { word: "Gymnastics",             category: "sports", difficulty: "easy",   hint: "Flipping, tumbling, balance beam, uneven bars — Summer Olympics" },
  { word: "Wrestling",              category: "sports", difficulty: "easy",   hint: "Grappling on a mat trying to pin your opponent's shoulders down" },
  { word: "Bowling",                category: "sports", difficulty: "easy",   hint: "Roll a heavy ball down a polished lane to knock down 10 pins" },
  { word: "Polo",                   category: "sports", difficulty: "medium", hint: "Riding horses and hitting a small ball with a long mallet" },
  { word: "Fencing",                category: "sports", difficulty: "medium", hint: "Olympic sword fighting sport — épée, foil, or sabre" },
  { word: "Rowing",                 category: "sports", difficulty: "medium", hint: "Pulling oars in sync with a crew to glide a long thin boat through water" },
  { word: "Karate",                 category: "sports", difficulty: "medium", hint: "Japanese martial art — punches, kicks, and breaking boards" },
  { word: "Triathlon",              category: "sports", difficulty: "medium", hint: "Race combining swimming, cycling, and running back to back" },
  { word: "Luge",                   category: "sports", difficulty: "medium", hint: "Lying face-up on a tiny sled and racing down an icy track at 90mph" },
  { word: "Curling",                category: "sports", difficulty: "medium", hint: "Sliding a granite stone on ice while teammates furiously sweep in front of it" },
  { word: "Skateboarding",          category: "sports", difficulty: "medium", hint: "Tricks on a wooden board with four wheels — kick flip, ollie" },
  { word: "Surfing",                category: "sports", difficulty: "medium", hint: "Standing on a board and riding ocean waves toward shore" },
  { word: "Skeet Shooting",         category: "sports", difficulty: "medium", hint: "Shotgun marksmanship — blast clay pigeons flung through the air" },
  { word: "Table Tennis",           category: "sports", difficulty: "medium", hint: "Ping pong — tiny paddle, tiny ball, tiny table" },
  { word: "Bobsled",                category: "sports", difficulty: "medium", hint: "Team of 2 or 4 racing down an icy track in a streamlined sled" },
  { word: "Synchronized Swimming",  category: "sports", difficulty: "medium", hint: "Team of swimmers performing perfectly timed choreography in a pool" },
  { word: "Pentathlon",             category: "sports", difficulty: "medium", hint: "Olympic competition with five different sports on the same day" },
  { word: "Rock Climbing",          category: "sports", difficulty: "medium", hint: "Competitive scaling of indoor or outdoor walls graded by difficulty" },
  { word: "Biathlon",               category: "sports", difficulty: "hard",   hint: "Winter Olympic sport combining cross-country skiing and rifle shooting" },
  { word: "Steeplechase",           category: "sports", difficulty: "hard",   hint: "Track race with water jumps and hurdles — horses or humans" },
  { word: "Equestrian Dressage",    category: "sports", difficulty: "hard",   hint: "Olympic event where a horse performs precise choreographed movements" },
  { word: "Rhythmic Gymnastics",    category: "sports", difficulty: "hard",   hint: "Gymnastics with ribbons, hoops, balls, and clubs — very flexible women" },
  { word: "Modern Pentathlon",      category: "sports", difficulty: "hard",   hint: "Olympic event: fencing, swimming, shooting, riding, and running in one day" },
  { word: "Canoe Polo",             category: "sports", difficulty: "hard",   hint: "Water sport where kayakers throw a ball through a suspended goal" },
  { word: "Underwater Hockey",      category: "sports", difficulty: "hard",   hint: "Hockey played on the bottom of a swimming pool while holding your breath" },
  { word: "Sepak Takraw",           category: "sports", difficulty: "hard",   hint: "Southeast Asian sport — volleyball but you can only use your feet and head" },
  { word: "Kabaddi",                category: "sports", difficulty: "hard",   hint: "South Asian contact sport — tag one person, hold your breath, say 'kabaddi'" },
  { word: "Jai Alai",               category: "sports", difficulty: "hard",   hint: "Basque sport — world's fastest ball game, players use a curved basket glove" },

  // ── TV SHOWS (30) ─────────────────────────────────────────
  { word: "Friends",                category: "tvshows", difficulty: "medium", hint: "Six friends in New York: 'How you doin'?' — Central Perk coffee shop" },
  { word: "Seinfeld",               category: "tvshows", difficulty: "medium", hint: "'A show about nothing' — Jerry, George, Elaine, Kramer in NYC" },
  { word: "The Office",             category: "tvshows", difficulty: "medium", hint: "Mockumentary about paper company employees in Scranton, PA" },
  { word: "Breaking Bad",           category: "tvshows", difficulty: "medium", hint: "Chemistry teacher diagnosed with cancer becomes a meth kingpin" },
  { word: "Game of Thrones",        category: "tvshows", difficulty: "medium", hint: "Dragons, ice zombies, and countless characters dying for the Iron Throne" },
  { word: "Stranger Things",        category: "tvshows", difficulty: "medium", hint: "80s kids in Indiana fight monsters from the Upside Down" },
  { word: "The Simpsons",           category: "tvshows", difficulty: "medium", hint: "Yellow cartoon family in Springfield — Homer, Marge, Bart, Lisa, Maggie" },
  { word: "South Park",             category: "tvshows", difficulty: "medium", hint: "Four foul-mouthed cartoon boys in a Colorado mountain town" },
  { word: "Black Mirror",           category: "tvshows", difficulty: "medium", hint: "Dark sci-fi anthology about the terrifying ways technology could go wrong" },
  { word: "The Crown",              category: "tvshows", difficulty: "medium", hint: "Netflix drama about Queen Elizabeth II and the British royal family" },
  { word: "Downton Abbey",          category: "tvshows", difficulty: "medium", hint: "Aristocratic English family and their servants in an early 20th century estate" },
  { word: "Sherlock",               category: "tvshows", difficulty: "medium", hint: "Modern BBC adaptation — Benedict Cumberbatch as genius detective" },
  { word: "Doctor Who",             category: "tvshows", difficulty: "medium", hint: "Time-traveling alien in a blue police phone box" },
  { word: "Grey's Anatomy",         category: "tvshows", difficulty: "medium", hint: "Long-running hospital drama — doctors fall in love and die dramatically" },
  { word: "The Walking Dead",       category: "tvshows", difficulty: "medium", hint: "Survivors navigate a post-apocalyptic world overrun with zombies" },
  { word: "Dexter",                 category: "tvshows", difficulty: "medium", hint: "Miami forensics expert moonlights as a vigilante serial killer" },
  { word: "Narcos",                 category: "tvshows", difficulty: "medium", hint: "True story of Pablo Escobar building a cocaine empire in Colombia" },
  { word: "Squid Game",             category: "tvshows", difficulty: "medium", hint: "Korean show — desperate players compete in deadly children's games for prize money" },
  { word: "Suits",                  category: "tvshows", difficulty: "medium", hint: "Brilliant college dropout pretends to be a Harvard lawyer at a NYC firm" },
  { word: "House",                  category: "tvshows", difficulty: "medium", hint: "Brilliant but rude doctor with a cane diagnoses impossible cases" },
  { word: "Twin Peaks",             category: "tvshows", difficulty: "hard",   hint: "David Lynch surreal mystery — FBI agent investigates a murder in a strange small town" },
  { word: "The Wire",               category: "tvshows", difficulty: "hard",   hint: "Gritty Baltimore crime drama showing both sides of the drug war" },
  { word: "Arrested Development",   category: "tvshows", difficulty: "hard",   hint: "Dysfunctional wealthy family loses everything — dense layered comedy" },
  { word: "Succession",             category: "tvshows", difficulty: "hard",   hint: "Ruthless billionaire media family fighting over who inherits the empire" },
  { word: "Fleabag",                category: "tvshows", difficulty: "hard",   hint: "British comedy where the lead character breaks the fourth wall constantly" },
  { word: "The Sopranos",           category: "tvshows", difficulty: "hard",   hint: "New Jersey mob boss goes to therapy while managing his crime family" },
  { word: "Battlestar Galactica",   category: "tvshows", difficulty: "hard",   hint: "Humanity flees robot Cylons through space searching for a new home called Earth" },
  { word: "Lost",                   category: "tvshows", difficulty: "hard",   hint: "Plane crash survivors on a strange island with polar bears and mysterious numbers" },
  { word: "Deadwood",               category: "tvshows", difficulty: "hard",   hint: "Profane Western about a lawless South Dakota gold rush town" },
  { word: "The Americans",          category: "tvshows", difficulty: "hard",   hint: "Soviet KGB spies living as ordinary Americans in 1980s Washington DC" },

];
